### ISSUE TITLE
Motors and encoders need to be tested

### ISSUE THREAD

**Issue by ManelMCCS** [ieeeupsb/Nemo#1]

**Comment by ManelMCCS** [comment]
Os motores estão bem montados ao contrário dos encoders. 
Penso que já sei qual será a falha no código de testes. Provavelmente o método dos testes precisa de definir a direção em que a roda vai girar

**Comment by LevyMitsugui** [comment]
Os motores foram testados: https://github.com/ieeeupsb/Nemo/issues/13

**Comment by ManelMCCS** [comment]
@LevyMitsugui os enconders já foram bem soldados?

**Comment by ManelMCCS** [comment]
Everything is working
